# Varsion de aplication.properties para Desarrollo

# Variable definida por mi
dev.info.enable=ture

##############################################
# Configuración de la base de datos MySQL
##############################################
spring.datasource.url=jdbc:mysql://localhost:3306/iw3_2025?createDatabaseIfNotExist=true&verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=iw3
spring.datasource.password=iw3pass